@startuml
left to right direction

actor "Администратор" as Admin
actor "Библиотекарь" as Librarian
actor "Читатель" as Reader

rectangle "Библиотека" {

package "Управление пользователями" {
Admin -- (Зарегистрировать библиотекаря)
Admin -- (Удалить библиотекаря)
Admin -- (Изменить пароль пользователя)
}

package "Работа с фондом" {
Librarian -- (Добавить описание книги)
Librarian -- (Добавить экземпляр книги)
Librarian -- (Списать экземпляр книги)
}

package "Обслуживание" {
Librarian -- (Выдать книгу)
Librarian -- (Принять книгу)
Librarian -- (Просмотреть просроченные книги)
}

package "Поиск и бронирование" {
Librarian -- (Искать книгу)
Librarian -- (Забронировать книгу)
Librarian -- (Отменить просроченное бронирование)

Reader -- (Искать книгу)
Reader -- (Забронировать книгу)
Reader -- (Отменить бронирование)

}

package "Учет читателей" {
Librarian -- (Добавить читателя)
}

package "Безопасность" {
Librarian -- (Изменить пароль)
}
}
@enduml
